### ISSUE TITLE
Limit-Sniper v0.23 Transaction failed with Presale on Dxsale

### ISSUE THREAD

**Issue by Lukas12111** [CryptoGnome/Limit-Sniper#10]
I tried to snipe 2 Coins today with the Limit-Sniper Mempool Bot v0.23, where both Tokens had a Presale on Dxsale. It detected Liquidity on both Coins, but on both Coins the Buy Transaction failed.

The first Coin was: BUSDoge(https://t.me/BUSDoge)
My Settings.json was:
"USECUSTOMNODE": "false",
        "CUSTOMNODE": "put your own node here if you want and make, USECUSTOMNODE = TRUE",
        "EXCHANGE": "pancakeswap",
		"DXSALE": "true",
        "DXPRESALECONTRACT": "0x0d4E3A46e2fC6874f9BE64a49222171BE5e9433b"

And my Tokens.json was:
{
    "ADDRESS": "0x4572713589430489D1CccE667a5Ff1cB48a979a5",
    "SYMBOL": "BUSDoge",
    "BUYAMOUNT": "0.013",
    "MULTIPLEBUYS": "false",
    "BUYCOUNT": "3",
    "RUGCHECK": "false"
  }

I used a different Wallet to snipe, then where i hold my Limit Tokens. The Txn Hash is: 0x97c9bece8585a46508518c48372bca96f60f9ce47565831c099c4f6976fa7d2c
The Bot saw Liquidity and did a normal buy transaction... but the Transaction failed. In the Error Log stands "INFO: 2021-07-13 20:03:18,816 Buy Sent Stopping Bot". 

The second Coin i Tried was Kingz Token(https://t.me/kingztoken)
My Settings.json was:
"USECUSTOMNODE": "false",
        "CUSTOMNODE": "put your own node here if you want and make, USECUSTOMNODE = TRUE",
        "EXCHANGE": "pancakeswap",
		"DXSALE": "true",
        "DXPRESALECONTRACT": "0x6824be4E4140badF486bC5BA57D0788f8F23c05d"

And my Tokens.json was:
{
    "ADDRESS": "0xb55850B90650380f296f1aC9306008Ad7A31AfEf",
    "SYMBOL": "Kingztoken",
    "BUYAMOUNT": "0.013",
    "MULTIPLEBUYS": "false",
    "BUYCOUNT": "3",
    "RUGCHECK": "false"
  }

On the second Coin i used the same Wallet where i hold the Limit Tokens to snipe. The Txn Hash is: 0x4bf10d6997fae55ebbe49dab3c31b925efd44ed24e4b61bda10f252a7ca9fc08

On this Token i don't know exactly what happened..but the Bot made a Transaction about 2 Minutes before the Token started. The Transaction failed. In the Error Log stands  "INFO: 2021-07-13 23:59:16,604 Buy Sent Stopping Bot"

I hope i can help to improve the Bot. Thank you very much.

**Comment by CryptoGnome** [comment]
hmm ok I have an idea i will start looking for a fix to this
