### ISSUE TITLE
FAILED TRANSACTIONS PANCAKESWAP

### ISSUE THREAD

**Issue by jjjuanx** [CryptoGnome/Limit-Sniper#15]
Hello. today I have scheduled the first token launch purchase with the bot and it has given me these errors:

INFO: 2021-07-14 20:54:31,173 *************************************************************************************
INFO: 2021-07-14 20:54:31,173 For Help & To Learn More About how the bot works please visit our wiki here:
INFO: 2021-07-14 20:54:31,173 https://cryptognome.gitbook.io/limitswap/
INFO: 2021-07-14 20:54:31,174 *************************************************************************************
INFO: 2021-07-14 20:54:33,596 Current $LIMIT Tokens Staked = 100.02064294531807

i put a little bit quantity of bnb for to buy and some transactions. i paste to continuation my configuratios:

[
    {
        
     
        "WALLETADDRESS": "0x8E315572a795d63ac801F10C0C034799A984dad9",

        "USECUSTOMNODE": "TRUE",
        "CUSTOMNODE": "https://bsc-dataseed.binance.org/",
        "EXCHANGE": "pancakeswap",
		"DXSALE": "false",
        "DXPRESALECONTRACT": "Insert DX SALE TOKEN CONTRACT ADDRESS HERE"
    }
]

  {
    "ADDRESS": "0x071fa11f7516cdeb366f7f7d91da5049f7086185",
    "SYMBOL": "RBOYS",
    "BUYAMOUNT": "0.09",
    "MULTIPLEBUYS": "true",
    "BUYCOUNT": "10",
    "RUGCHECK": "true"
  }
]

i wait your response. thanks.

**Comment by jjjuanx** [comment]
link to failed transactions:

https://bscscan.com/tx/0x9d5b2e773a254c3a9f717ef93f799c33d22ce9e91e7a288370dcb7cb5370731c
https://bscscan.com/tx/0x6165a4f05a6f92fe93b3cb38df3618d04d7d03e2105db81608bd09048c588bd5
https://bscscan.com/tx/0xe160f6d61d0c450ba6d55c19ae46faa552d0d2d47bd4f5a46dec2c04cf66d378
https://bscscan.com/tx/0xea33e91104974d98a22bf290fd7a8b8125d8f523b846a62a8ca2cccc41622c2b
https://bscscan.com/tx/0x5ece8bf2c472ad3cd184bb6e27b9d98d34888fdc8e7691427fade4f446bcbdaa
....

**Comment by kakao789** [comment]
it seems to me tx failed due to low gas limit. had the same issue with a sniper

**Comment by CryptoGnome** [comment]
#19
