### ISSUE TITLE
Sniper Bot (Auto Configure to Buy the Max Amount of Tokens allowed by Contract)

### ISSUE THREAD

**Issue by noblesse11** [CryptoGnome/Limit-Sniper#18]
Hi, not sure why this isn't already an option for the sniper & limit buy bot since 99% of the new projects now employ buy limit in their projects.

Reason why it should be an option (true or false) is because most of the time the dev gives out contract address at last minute without mentioning the buy limit.

So it would be nice if we could just submit a fixed number of ETH to be used to purchase the maximum amount of tokens allowed by the contract and then have the balance of the amount returned back to our wallets.

I have seen this done by other users many times. Here's an example of what i meant:

https://ibb.co/WzmFX9C

The guy used 0.1 ETH as the fixed number of ETH to purchase the maximum amount of tokens allowed by the contract (which is 0.0259 ETH in this case) and have the remaining balance returned back to his wallet.

Thank you.

**Comment by CryptoGnome** [comment]
this is not possible, you need to do your own due diligence and calculate this
