### ISSUE TITLE
Dudes and fails

### ISSUE THREAD

**Issue by jjjuanx** [CryptoGnome/Limit-Sniper#21]
hi, i'm having trouble with the sniper, and i'd like to ask a questions: 

1: If I use the bot on two different computers, but with the same limitwallet, will this slow them down?  

2: Does a quick purchase depend on my internet speed?

  yesterday I used the sniper in the same coin but in two different houses, one bought in block 3 and the other in block 27. This translates into money losses.  I would like to know why you have bought so expensive.  

link of when they added the liquidity:
https://bscscan.com/tx/0xd354d29563fb315400390b7bb72b84915e21ae996afcd42bfd9051145ed1f7f3

 a link of my first purchase 3 blocks after adding the liquidity: 
https://bscscan.com/tx/0xb25945fe0260cf12992cac14a0d4129b9e27909234476631fa1470958545c77e

and a link to the other purchase in block 24:

https://bscscan.com/tx/0xd9bd2d9e1bdee9e560d2584b346bcf9a5567e626c4567a7fb3618eac61d71e6e

The same config in the sniper tokkens.

BUYAMOUN 0.07BNB
BUYCOUNT 8

**Comment by CryptoGnome** [comment]
1.) you should not run more than one bot per wallet, the nonces can get confused.
2.) YES
