### ISSUE TITLE
Request for Dxsale Trigger Option

### ISSUE THREAD

**Issue by Lukas12111** [CryptoGnome/Limit-Sniper#25]
Hello,

I just open this Issue with what you already mentioned on the Limitswap Telegram Group. If another DXpresale adds liquidity it'll trigger our bots to buy even though it won't go through because it's not the coin we have it set up for. And there are always a few coins with DXpresale who are launching at the same time. So it would be amazing if we have an option for this that the Sniper bot keeps running till it buys on right coin in the next Update.

Thank you very much.

**Comment by CryptoGnome** [comment]
we can't , you need to monitor this
