### ISSUE TITLE
tokens with liquidity but untradable for a moment

### ISSUE THREAD

**Issue by tagkar** [CryptoGnome/Limit-Sniper#26]
As i mentioned in telegram i had several failed trades with tokens which released their cash but could not be traded right away. Limitswap and Sniper tried to buy but were unsuccessful. Limiswap doesn't stop trying to buy and fees are lost every time.
For exemple this token: https://bscscan.com/address/0xe6E6A022b4d4e538Ca0a1f47941CbBF3F9cc1467#code
and this one: https://bscscan.com/address/0x1eca0f549ef9b42fa1933e70a15b2db437ab0a84#code. It seems the first have go live fonction but not the second one. 
I'me giving you my wallet bscan to see the failed transactions. block 9635673 for the first token and 9613371 to 9612895 for the second (I was not in front of my computer for this one)
https://bscscan.com/address/0x217e855768953a5417db878a4d0c2f8c7d9d7314
Thanks for your hard work

**Comment by CryptoGnome** [comment]
we don't support this atm  stay away from these contracts
