### ISSUE TITLE
Requesting DxSale support

### ISSUE THREAD

**Issue by Lukas12111** [CryptoGnome/Limit-Sniper#4]
As you wrote on my last Ticket/Issue...i am creating here a new ticket with the request that the Limit Sniper Mempool Bot can detect Liquidity when a Token launches on Pancakeswap, when the Token had a presale on Dxsale. I don't mean to snipe on the DxSale Site for the Presale. I mean after the Presale when its adding liquidity and then Launches on pancakeswap. Because everyday there are a lot of Coins who are launching like that these days. And most of the times they are not scams. Unlike the so called "Fair launches" or "normal launches" without Presale. These Tokens are 90 percent scams today in my experience...especially on BSC. Therefore i am not sniping these fair launches anymore on BSC...too much money I lost. So it would be amazing and changing the game for me if the mempool Bot will detect Liquidity on Coins which had a presale on DxSale, when they Lauch on Pancakeswap. Thank you very much.

**Comment by CryptoGnome** [comment]
Please link Dxsale contracts and document for me

**Comment by Lukas12111** [comment]
These are a few Contracts of Coins who had a presale on DxSale, and then launched on Pancakeswap:

Daddy Doge(https://t.me/daddydogetoken) CA: 0x7cce94c0b2c8ae7661f02544e62178377fe8cf92

MOMOSHIBA BSC(https://t.me/momoshibabsc) CA: 0x843e0cEbB6da822F553b4c1DaA234be87491Ab31

Cockapoo(https://t.me/cockapootoken) CA: 0xb277db4f19fc79f87569ac34eff5d1d50d4aeb8b

BabyDoge Classic(https://t.me/babydogeclassicbsc) CA: 0x44ab23e35b57b7093ea0e525dfafcdd226672058

It would be amazing if the Mempool Bot is able to detect Liquidity when Coins like this are launching on Pancakeswap. Thank you very much.

**Comment by CryptoGnome** [comment]
Adding next release
