### ISSUE TITLE
Mempool Bot v0.22 Issue wit Presale on DxSale

### ISSUE THREAD

**Issue by Lukas12111** [CryptoGnome/Limit-Sniper#8]
I just tried to Snipe a coin which had a presale on DxSale with the Mempool Bot v.022. But the Bot never detected Liquidity. So it never made a Buy Transaction. The Error File is empty. My Tokens.json was :

[
  {
    "ADDRESS": "0x5fe023d72231D97b8Df7F679d01228f6Ba77A585",
    "SYMBOL": "WhoisyourDoge",
    "BUYAMOUNT": "0.013",
    "MULTIPLEBUYS": "false",
    "BUYCOUNT": "3",
    "RUGCHECK": "false"
  }
]

My Settings json was:

"USECUSTOMNODE": "false",
        "CUSTOMNODE": "put your own node here if you want and make, USECUSTOMNODE = TRUE",
        "EXCHANGE": "pancakeswap",
		"DXSALE": "true",
        "DXPRESALECONTRACT": "0x333BA4C5572046c50B52608A6e80C18C7E15ed4A"

The Coin was WhosyourDoge(https://t.me/WhosYourDoge). CA:0x5fe023d72231D97b8Df7F679d01228f6Ba77A585 Presale Adresse on Dxsale: 0x333BA4C5572046c50B52608A6e80C18C7E15ed4A

Also i use a different Wallet to snipe than the Wallet my Limit Tokens are. Thank you very much.

**Comment by CryptoDynasty** [comment]
I can verify the same information. Tested V .22 on two different DXsales today as well and both times Sniper just continues to wait for liquidity event and never buys.
